POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiZTAyYTE3YjAtY2Y3Yi00ZmJhLWIwMzQtOTc0NWEzYWMxODM4IiwiZXhwIjoxNzczMjQ0MjExLCJpYXQiOjE3NzMyNDA2MTF9.74_g3VAMTdHOsyNyzIqfusKDd5VWxUOMUvwykTRul8Y


{
    "body": "Hello there"
}

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiZTAyYTE3YjAtY2Y3Yi00ZmJhLWIwMzQtOTc0NWEzYWMxODM4IiwiZXhwIjoxNzczMjQ0MjExLCJpYXQiOjE3NzMyNDA2MTF9.74_g3VAMTdHOsyNyzIqfusKDd5VWxUOMUvwykTRul8Y

{
    "body": "Hello there Hello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello thereHello there"
}

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "extra": "this should be ignored",
  "user_id": "123e4567-e89b-12d3-a456-426614174000"
}

###

GET http://localhost:8080/api/healthz HTTP/1.1

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
    "email": "test@example.co",
    "password": "Password123$"
}

###

POST http://localhost:8080/api/login HTTP/1.1

{
    "email": "test@example.co",
    "password": "Password123$"
}

###
POST http://localhost:8080/admin/reset HTTP/1.1

###
GET http://localhost:8080/api/chirps HTTP/1.1

###

POST http://localhost:8080/api/refresh HTTP/1.1
Authorization: Bearer 

###

PUT http://localhost:8080/api/refresh HTTP/1.1
Authorization: Bearer 

{
    "email": "new@example.co",
    "password": "NewPassword123$"
}

###

DELETE  http://localhost:8080/api/chirps/{chirpID} HTTP/1.1
Authorization: Bearer 

###